refs = [
    "./codebase.md",
    "./theming.md",
    "./ideas.md",
    "./extensions.md",
]

[meta]
title = "sych"
authors = ["codekidX"]
version = "0.1.0"
description = "sych generates docs from .md files in your project"

[doc]
root = "./docs"

[extensions]
request = "http://localhost:8000/snooze.js"
